# Generated by Django 4.0.4 on 2023-03-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientereceta',
            old_name='username',
            new_name='first_name',
        ),
    ]
