# Generated by Django 4.0.4 on 2023-03-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
