# Generated by Django 4.0.4 on 2023-03-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFamiliar',
            fields=[
                ('id_usuario_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('num_run_familiar', models.CharField(max_length=12)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('apellido_familiar', models.CharField(max_length=100)),
                ('email_familiar', models.EmailField(max_length=254)),
                ('telefono_familiar', models.IntegerField()),
                ('whatsapp_familiar', models.IntegerField()),
                ('celular_familiar', models.IntegerField()),
                ('telegram_familiar', models.IntegerField()),
                ('parentesco', models.CharField(max_length=100)),
                ('direccion_familiar', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
        ),
    ]
