# Generated by Django 4.0.4 on 2023-02-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Cotizacion'], [2, 'Sugerencia'], [3, 'Felicitaciones'], [4, 'Reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
