# Generated by Django 4.0.4 on 2023-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_pacientereceta_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientereceta',
            old_name='first_name',
            new_name='nombres_paciente',
        ),
    ]
