# Generated by Django 4.0.4 on 2023-03-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuariofamiliar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CESFAM',
            fields=[
                ('id_cesfam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_CESFAM', models.CharField(max_length=200)),
                ('direccion_CESFAM', models.CharField(max_length=200)),
                ('email_CESFAM', models.CharField(max_length=200)),
                ('telefono_CESFAM', models.CharField(max_length=200)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
        ),
    ]
