# Generated by Django 4.0.4 on 2023-02-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run_familiar', models.CharField(max_length=12)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('apellido_familiar', models.CharField(max_length=100)),
                ('direccion_familiar', models.CharField(max_length=100)),
                ('email_familiar', models.EmailField(max_length=254)),
                ('telefono_familiar', models.IntegerField()),
                ('whatsapp_familiar', models.IntegerField()),
                ('celular_familiar', models.IntegerField()),
                ('telegram_familiar', models.IntegerField()),
                ('nombre_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_receta', models.DateField()),
                ('horario_recordatorio', models.DateTimeField()),
                ('descripcion_receta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='nombre',
            new_name='nombre_laboratorio',
        ),
        migrations.RenameField(
            model_name='medicamentos',
            old_name='nombre',
            new_name='nombre_comercial',
        ),
        migrations.RenameField(
            model_name='medicamentos',
            old_name='principio',
            new_name='nombre_princio_activo',
        ),
        migrations.RenameField(
            model_name='principio',
            old_name='nombre',
            new_name='nombre_princio_activo',
        ),
        migrations.RenameField(
            model_name='viaadminstracion',
            old_name='nombre',
            new_name='nombre_via_administracion',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run_usuario', models.CharField(max_length=12)),
                ('nombres_usuario', models.CharField(max_length=100)),
                ('apellido_paterno_usuario', models.CharField(max_length=100)),
                ('appelido_materno_usuario', models.CharField(max_length=100)),
                ('dirreccion_usuario', models.CharField(max_length=150)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('telefono_usuario', models.IntegerField()),
                ('celular_usuario', models.IntegerField()),
                ('whatsapp_usuario', models.IntegerField()),
                ('nombre_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.medicamentos')),
                ('nombre_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
                ('nombre_familiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.familiar')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recordatorio', models.CharField(max_length=100)),
                ('hora_recordatorio', models.DateTimeField()),
                ('descripcion_receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('nombre_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
        ),
        migrations.AddField(
            model_name='familiar',
            name='nombre_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombre_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
        ),
    ]
