# Generated by Django 4.0.4 on 2023-03-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_usuario',
            old_name='id_tipo_usuario',
            new_name='id_TipoUsuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_tipo_usuario',
            new_name='id_TipoUsuario',
        ),
    ]
