# Generated by Django 4.0.4 on 2023-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_first_name_pacientereceta_nombres_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoFraccionamiento',
            fields=[
                ('id_fraccion', models.AutoField(primary_key=True, serialize=False)),
                ('fraccion', models.CharField(max_length=4)),
                ('descripcion_fraccion', models.CharField(max_length=200)),
            ],
        ),
    ]
