# Generated by Django 4.2.1 on 2023-05-16 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_profesionalpaciente_identificacicion_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesionalpaciente", name="ficha_clinica_paciente",
        ),
        migrations.AlterField(
            model_name="profesionalpaciente",
            name="identificacion_profesional",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("tipo_usuario_id", 2), ("tipo_usuario_id", 7), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Rprofesional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
