# Generated by Django 4.0.4 on 2023-03-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cesfam'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargadoQuimicoFarmaceutico',
            fields=[
                ('id_quimico_farmaceutio', models.AutoField(primary_key=True, serialize=False)),
                ('registro_sanitario_QF', models.CharField(max_length=200)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipo_usuario')),
            ],
        ),
    ]
