# Generated by Django 4.0.4 on 2023-03-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_id_tipo_usuario_tipo_usuario_id_tipousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_TipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipo_usuario'),
        ),
    ]
