# Generated by Django 4.0.4 on 2023-03-16 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuario_id_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioficha',
            name='id_tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarioficha',
            name='num_run_usuario',
        ),
        migrations.AddField(
            model_name='usuarioficha',
            name='id_TipoUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipo_usuario'),
        ),
        migrations.AddField(
            model_name='usuarioficha',
            name='rut_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
