# Generated by Django 4.0.4 on 2023-03-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_farmaciacesfam'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaciasucursal',
            name='id_quimico_farmaceutio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.encargadoquimicofarmaceutico'),
            preserve_default=False,
        ),
    ]
