# Generated by Django 4.0.4 on 2023-03-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_enfermera_celular_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientereceta',
            name='fracionamiento_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicamentofraccionamiento'),
        ),
    ]
