# Generated by Django 4.1 on 2023-06-10 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_usuarioficha_identificacion_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cesfam",
            name="identificacion_cesfam",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 5)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="CESFAM",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pacientefamiliar",
            name="identificacion_familiar",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 3)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="PacienteFamiliar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pacientefichaclinica",
            name="identificacion_paciente",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 2)),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="FCPaciente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pacientereceta",
            name="nombres_paciente",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 2)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="RRPaciente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profesionalpaciente",
            name="identificacicion_usuario",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 2)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Rpaciente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profesionalpaciente",
            name="identificacion_profesional",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("tipo_usuario_id", 4), ("tipo_usuario_id", 6), _connector="OR"
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Rprofesional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quimicofarmaceuticoencargado",
            name="identificacion_QF",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 4)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="QUIMICO",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usuarioficha",
            name="identificacion_usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Enfermera",),
    ]
