# Generated by Django 4.1 on 2023-06-13 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_cesfam_identificacion_cesfam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profesionalpaciente",
            name="identificacion_profesional",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("tipo_usuario_id", 6)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Rprofesional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
