# Generated by Django 4.0.4 on 2023-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pacientereceta_horario_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientereceta',
            name='horario_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientereceta',
            name='horario_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientereceta',
            name='horario_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientereceta',
            name='horario_5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientereceta',
            name='horario_6',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
