# Generated by Django 4.1 on 2023-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_contacto_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="contacto", name="timestamp",),
        migrations.AddField(
            model_name="contacto",
            name="telefono",
            field=models.IntegerField(default=99999999),
            preserve_default=False,
        ),
    ]
