# Generated by Django 4.1 on 2023-06-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_contacto_timestamp_contacto_telefono"),
    ]

    operations = [
        migrations.DeleteModel(name="FamiliarPacienteUsuario",),
    ]
