# Generated by Django 4.1 on 2023-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_pacientefamiliar_identificacion_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesionalpaciente",
            name="horario_turno",
            field=models.IntegerField(
                choices=[
                    [0, "Mañana"],
                    [1, "Tarde"],
                    [2, "Madrugada"],
                    [3, "24 Horas"],
                ],
                null=True,
            ),
        ),
    ]
