# Generated by Django 4.1 on 2023-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_profesionalpaciente_horario_turno"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuarioficha", name="email_usuario",),
        migrations.AddField(
            model_name="contacto",
            name="repetir_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
