# Generated by Django 4.1 on 2023-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_usuarioficha_email_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuarioficha", name="telegram_usuario",),
        migrations.RemoveField(model_name="usuarioficha", name="whatsapp_usuario",),
    ]
