# Generated by Django 4.1 on 2023-06-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_contacto_timestamp"),
    ]

    operations = [
        migrations.RemoveField(model_name="contacto", name="timestamp",),
    ]
