# Generated by Django 4.1 on 2023-06-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_contacto_delete_contactoss"),
    ]

    operations = [
        migrations.RemoveField(model_name="contacto", name="timestap",),
    ]
