# Generated by Django 4.1 on 2023-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_contacto_timestap"),
    ]

    operations = [
        migrations.DeleteModel(name="Contacto",),
    ]
