# Generated by Django 4.1 on 2023-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_contacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentos",
            name="imagen",
            field=models.ImageField(null=True, upload_to="medicamentos"),
        ),
    ]
