# Generated by Django 4.1 on 2023-06-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_medicamentos_imagen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarioficha", old_name="id_usuario", new_name="id",
        ),
    ]
