# Generated by Django 4.1 on 2023-06-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_carrito_itemcarrito_carrito_medicamentos_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemcarrito", name="carrito",),
        migrations.RemoveField(model_name="itemcarrito", name="medicamento",),
        migrations.DeleteModel(name="Carrito",),
        migrations.DeleteModel(name="ItemCarrito",),
    ]
