# Generated by Django 4.1 on 2023-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_remove_itemcarrito_carrito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamentos",
            name="precio",
            field=models.IntegerField(default=0),
        ),
    ]
