# Generated by Django 4.1 on 2023-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_medicamentos_precio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioficha",
            name="imagen",
            field=models.ImageField(null=True, upload_to="perfil_usuario"),
        ),
    ]
