# Generated by Django 4.1 on 2023-06-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_remove_medicamentos_cantidad_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockFarmacia",
            fields=[
                ("id_stock", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_vencimiento", models.DateField()),
                ("cantidad", models.IntegerField()),
                ("precio", models.IntegerField(default=0)),
                (
                    "farmacia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.farmacia"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.medicamentos",
                    ),
                ),
            ],
        ),
    ]
