# Generated by Django 4.1 on 2023-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_stockfarmacia_farmacia"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmaciasucursal",
            name="lat",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="farmaciasucursal",
            name="lng",
            field=models.CharField(default="", max_length=200),
        ),
    ]
